
CREATE TABLE ACCOUNT (
ID BIGINT IDENTITY PRIMARY KEY, OWNER_NAME VARCHAR(255), BALANCE DOUBLE,
ACCESS_TIME TIMESTAMP,
LOCKED BOOLEAN
);

INSERT INTO ACCOUNT(ID,OWNER_NAME,BALANCE, ACCESS_TIME , LOCKED ) VALUES(100,'owner-1',10,'2014-01-01',false);
INSERT INTO ACCOUNT(ID,OWNER_NAME,BALANCE, ACCESS_TIME , LOCKED ) VALUES(101,'owner-2',0,'2014-01-01',false);
